# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_asc_attack.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import PyQt5
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
import pyttsx3
from PyQt5.Qt import QApplication, QWidget, QPushButton,QThread,QMutex,QButtonGroup
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import pyqtSignal
from PyQt5.QtCore import QUrl, QPointF, QLineF, Qt, QTimer


class Ui_asc_attack(object):
    def setupUi(self, ASC_Attack):
        ASC_Attack.setObjectName("CNN_dataset_test")
        ASC_Attack.resize(1327, 874)
        font = QtGui.QFont()
        font.setPointSize(10)
        ASC_Attack.setFont(font)
        self.label_2 = QtWidgets.QLabel(ASC_Attack)
        self.label_2.setGeometry(QtCore.QRect(55, 20, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(ASC_Attack)
        self.pushButton.setGeometry(QtCore.QRect(126, 147, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_image_show = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show.setGeometry(QtCore.QRect(153, 220, 261, 261))
        self.label_image_show.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show.setText("")
        self.label_image_show.setObjectName("label_image_show")
        self.label = QtWidgets.QLabel(ASC_Attack)
        self.label.setGeometry(QtCore.QRect(199, 488, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(ASC_Attack)
        self.label_3.setGeometry(QtCore.QRect(199, 824, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.radioButton = QtWidgets.QRadioButton(ASC_Attack)
        self.radioButton.setGeometry(QtCore.QRect(55, 80, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(ASC_Attack)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(ASC_Attack)
        self.radioButton_3.setGeometry(QtCore.QRect(430, 80, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_image_show_2 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_2.setGeometry(QtCore.QRect(153, 560, 261, 261))
        self.label_image_show_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_2.setText("")
        self.label_image_show_2.setObjectName("label_image_show_2")
        self.label_image_show_3 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_3.setGeometry(QtCore.QRect(554, 220, 261, 261))
        self.label_image_show_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_3.setText("")
        self.label_image_show_3.setObjectName("label_image_show_3")
        self.label_4 = QtWidgets.QLabel(ASC_Attack)
        self.label_4.setGeometry(QtCore.QRect(590, 488, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_image_show_4 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_4.setGeometry(QtCore.QRect(552, 561, 261, 261))
        self.label_image_show_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_4.setText("")
        self.label_image_show_4.setObjectName("label_image_show_4")
        self.label_5 = QtWidgets.QLabel(ASC_Attack)
        self.label_5.setGeometry(QtCore.QRect(590, 824, 199, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(ASC_Attack)
        self.label_6.setGeometry(QtCore.QRect(220, 510, 72, 131))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_image_show_5 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_5.setGeometry(QtCore.QRect(1040, 11, 251, 251))
        self.label_image_show_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_5.setText("")
        self.label_image_show_5.setObjectName("label_image_show_5")
        self.label_7 = QtWidgets.QLabel(ASC_Attack)
        self.label_7.setGeometry(QtCore.QRect(1046, 270, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(ASC_Attack)
        self.label_8.setGeometry(QtCore.QRect(1046, 558, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_image_show_6 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_6.setGeometry(QtCore.QRect(1040, 305, 251, 251))
        self.label_image_show_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_6.setText("")
        self.label_image_show_6.setObjectName("label_image_show_6")
        self.label_9 = QtWidgets.QLabel(ASC_Attack)
        self.label_9.setGeometry(QtCore.QRect(1046, 840, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_image_show_7 = QtWidgets.QLabel(ASC_Attack)
        self.label_image_show_7.setGeometry(QtCore.QRect(1040, 590, 251, 251))
        self.label_image_show_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_image_show_7.setText("")
        self.label_image_show_7.setObjectName("label_image_show_7")

        self.Arrow1 = QtWidgets.QWidget(ASC_Attack)
        self.Arrow1.setGeometry(QtCore.QRect(230, 480, 120, 80))
        self.Arrow1.setObjectName("Arrow1")
        self.Arrow2 = QtWidgets.QWidget(ASC_Attack)
        self.Arrow2.setGeometry(QtCore.QRect(409, 479, 141, 81))
        self.Arrow2.setObjectName("Arrow2")
        self.Arrow3 = QtWidgets.QWidget(ASC_Attack)
        self.Arrow3.setGeometry(QtCore.QRect(620, 480, 120, 80))
        self.Arrow3.setObjectName("Arrow3")

        self.timer = QTimer()
        self.count = 0
        self.timer.timeout.connect(self.image_played_visible)

        btngroup1 = QButtonGroup(ASC_Attack)
        btngroup1.addButton(self.radioButton)
        btngroup1.addButton(self.radioButton_2)
        btngroup1.addButton(self.radioButton_3)

        self.dataset_name = '2S1'
        self.data_dir = 'Data/MSTAR_ASC/2S1_14935'
        self.openimage(image_show=self.label_image_show, imgName='Data/MSTAR_ASC/2S1_14935/ORI_IMG.png')
        self.retranslateUi(ASC_Attack)
        QtCore.QMetaObject.connectSlotsByName(ASC_Attack)

    def retranslateUi(self, CNN_dataset_test):
        _translate = QtCore.QCoreApplication.translate
        CNN_dataset_test.setWindowTitle(_translate("CNN_dataset_test", "ASC Physical Characteristic Attack"))
        CNN_dataset_test.setWindowIcon(QIcon("./1.ico"))
        self.label_2.setText(_translate("CNN_dataset_test", "Choose the class in MSTAR："))
        self.pushButton.setText(_translate("CNN_dataset_test", "Start to output"))
        self.label.setText(_translate("CNN_dataset_test", "Original data"))
        self.label_3.setText(_translate("CNN_dataset_test", "Target segmentation"))
        self.radioButton.setText(_translate("CNN_dataset_test", " 2S1"))
        self.radioButton_2.setText(_translate("CNN_dataset_test", " BMP2"))
        self.radioButton_3.setText(_translate("CNN_dataset_test", " D7"))
        self.label_4.setText(_translate("CNN_dataset_test", "ASC reconstruction"))
        self.label_5.setText(_translate("CNN_dataset_test", "Adversarial Example"))
        self.label_7.setText(_translate("CNN_dataset_test", "Perturbations"))
        self.label_8.setText(_translate("CNN_dataset_test", "Peak plot in original data"))
        self.label_9.setText(_translate("CNN_dataset_test", "Peak plot in adversarial data"))
        self.radioButton.setChecked(True)

    def caolianjie(self):
        self.radioButton.toggled.connect(self.dataset_select_set_visible)
        self.radioButton_2.toggled.connect(self.dataset_select_set_visible)
        self.radioButton_3.toggled.connect(self.dataset_select_set_visible)
        self.pushButton.clicked.connect(self.startCount)

    def dataset_select_set_visible(self):
        if self.radioButton.isChecked():
            self.dataset_name = '2S1'
            self.data_dir = 'Data/MSTAR_ASC/2S1_14935'
            self.openimage(image_show=self.label_image_show,imgName='Data/MSTAR_ASC/2S1_14935/ORI_IMG.png')
        elif self.radioButton_2.isChecked():
            self.dataset_name = 'BMP2'
            self.data_dir = 'Data/MSTAR_ASC/BMP2_03446'
            self.openimage(image_show=self.label_image_show,imgName='Data/MSTAR_ASC/BMP2_03446/ORI_IMG.png')
        elif self.radioButton_3.isChecked():
            self.dataset_name = 'D7'
            self.data_dir = 'Data/MSTAR_ASC/D7_15086'
            self.openimage(image_show=self.label_image_show,imgName='Data/MSTAR_ASC/D7_15086/ORI_IMG.png')

    def openimage(self,image_show,imgName):
        jpg = QtGui.QPixmap(imgName).scaled(self.label_image_show.width(), self.label_image_show.height())
        image_show.setPixmap(jpg)

    def image_played_visible(self):
        if self.dataset_name == "2S1":
            self.count = self.count + 1
            self.openimage(image_show=self.label_image_show_2,imgName='Data/MSTAR_ASC/2S1_14935/ORI_SEG.png')
            if self.count == 2:
                self.openimage(image_show=self.label_image_show_3,imgName='Data/MSTAR_ASC/2S1_14935/ASC_RECON.png')
            if self.count == 4:
                self.openimage(image_show=self.label_image_show_4,imgName="Data/MSTAR_ASC/2S1_14935/ADV_IMG.png")
            if self.count == 6:
                self.openimage(image_show=self.label_image_show_5,imgName="Data/MSTAR_ASC/2S1_14935/NOISE_IMG.png")
            if self.count == 8:
                self.openimage(image_show=self.label_image_show_6,imgName="Data/MSTAR_ASC/2S1_14935/ORI_PEAK.png")
            if self.count == 10:
                self.openimage(image_show=self.label_image_show_7,imgName='Data/MSTAR_ASC/2S1_14935/ASC_PEAK.png')
                self.timer.stop()

        elif self.dataset_name == "BMP2":
            self.count = self.count + 1
            self.openimage(image_show=self.label_image_show_2,imgName='Data/MSTAR_ASC/BMP2_03446/ORI_IMG.png')
            if self.count == 2:
                self.openimage(image_show=self.label_image_show_3,imgName='Data/MSTAR_ASC/BMP2_03446/ASC_RECON.png')
            elif self.count == 4:
                self.openimage(image_show=self.label_image_show_4,imgName="Data/MSTAR_ASC/BMP2_03446/ADV_IMG.png")
            elif self.count == 6:
                self.openimage(image_show=self.label_image_show_5,imgName="Data/MSTAR_ASC/BMP2_03446/NOISE_IMG.png")
            elif self.count == 8:
                self.openimage(image_show=self.label_image_show_6,imgName="Data/MSTAR_ASC/BMP2_03446/ORI_PEAK.png")
            elif self.count == 10:
                self.openimage(image_show=self.label_image_show_7,imgName='Data/MSTAR_ASC/BMP2_03446/ASC_PEAK.png')
                self.timer.stop()

        elif self.dataset_name == "D7":
            self.count = self.count + 1
            self.openimage(image_show=self.label_image_show_2,imgName='Data/MSTAR_ASC/D7_15086/ORI_IMG.png')
            if self.count == 2:
                self.openimage(image_show=self.label_image_show_3,imgName='Data/MSTAR_ASC/D7_15086/ASC_RECON.png')
            elif self.count == 4:
                self.openimage(image_show=self.label_image_show_4,imgName="Data/MSTAR_ASC/D7_15086/ADV_IMG.png")
            elif self.count == 6:
                self.openimage(image_show=self.label_image_show_5,imgName="Data/MSTAR_ASC/D7_15086/NOISE_IMG.png")
            elif self.count == 8:
                self.openimage(image_show=self.label_image_show_6,imgName="Data/MSTAR_ASC/D7_15086/ORI_PEAK.png")
            elif self.count == 10:
                self.openimage(image_show=self.label_image_show_7,imgName='Data/MSTAR_ASC/D7_15086/ASC_PEAK.png')
                self.timer.stop()

    def startCount(self):
        self.timer.start(1000)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    interface = QtWidgets.QDialog()
    ui = Ui_asc_attack()
    ui.setupUi(interface)
    ui.caolianjie()
    interface.show()
    sys.exit(app.exec_())












